# Generated by Django 2.2.3 on 2019-07-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='name',
            field=models.TextField(),
        ),
    ]
