# Generated by Django 2.2.3 on 2019-07-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField()),
                ('snp', models.FloatField()),
                ('nasdaq', models.FloatField()),
                ('russell', models.FloatField()),
                ('eurostoxx', models.FloatField()),
                ('topix', models.FloatField()),
                ('mem', models.FloatField()),
                ('mar', models.FloatField()),
                ('wti_idx', models.FloatField()),
                ('agr_idx', models.FloatField()),
                ('silver_idx', models.FloatField()),
                ('gold_idx', models.FloatField()),
                ('high_yield', models.FloatField()),
                ('igb', models.FloatField()),
                ('ltb', models.FloatField()),
                ('skb', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField()),
                ('snp', models.FloatField()),
                ('nasdaq', models.FloatField()),
                ('russell', models.FloatField()),
                ('eurostoxx', models.FloatField()),
                ('topix', models.FloatField()),
                ('mem', models.FloatField()),
                ('mar', models.FloatField()),
                ('wti_idx', models.FloatField()),
                ('agr_idx', models.FloatField()),
                ('silver_idx', models.FloatField()),
                ('gold_idx', models.FloatField()),
                ('high_yield', models.FloatField()),
                ('igb', models.FloatField()),
                ('ltb', models.FloatField()),
                ('skb', models.FloatField()),
            ],
        ),
    ]
