# Generated by Django 2.2.3 on 2019-07-22 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_monthlycompat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlycompat',
            old_name='ticker_id',
            new_name='ticker',
        ),
    ]
