# Generated by Django 2.2.3 on 2019-07-22 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_auto_20190716_0942'),
        ('price', '0003_auto_20190722_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('isEndofMonth', models.BooleanField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Ticker')),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyCompat',
        ),
    ]
