# Generated by Django 2.2.3 on 2019-07-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateTimeField()),
                ('snp', models.FloatField(default=0)),
                ('nasdaq', models.FloatField(default=0)),
                ('russell', models.FloatField(default=0)),
                ('eurostoxx', models.FloatField(default=0)),
                ('topix', models.FloatField(default=0)),
                ('mem', models.FloatField(default=0)),
                ('mar', models.FloatField(default=0)),
                ('wti_idx', models.FloatField(default=0)),
                ('agr_idx', models.FloatField(default=0)),
                ('silver_idx', models.FloatField(default=0)),
                ('gold_idx', models.FloatField(default=0)),
                ('high_yield', models.FloatField(default=0)),
                ('igb', models.FloatField(default=0)),
                ('ltb', models.FloatField(default=0)),
                ('skb', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
