# Generated by Django 2.2.3 on 2019-07-24 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestReport',
            new_name='Portfolio',
        ),
    ]
